# ワークフロー名
name: schedule_tweet

on:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      # リポジトリからチェックアウトして以下の処理を実行していく
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # pipを更新
          python -m pip install --upgrade pip
          # 必要なパッケージをインストール
          pip install line-bot-sdk
          pip install tweepy
          pip install sympy
          pip install pytz
      - name: Run script
        run: |
          # tweet.pyの実行
          python tweet.py
